############################################
## GLOBAL VARIABLES
############################################

# @BaseUrl = https://pam-2026-p4-ifs23016-be.delcom.org:8080
@BaseUrl = http://127.0.0.1:8000

@plantId =
@bookId =


############################################
## PROFILE
############################################

### Get Profile
# @name GetProfile
GET {{BaseUrl}}/profile
Accept: application/json


### Get Profile Photo
# @name GetProfilePhoto
GET {{BaseUrl}}/profile/photo
Accept: application/json

## Plants
## ===========================================

### Mengambil semua data tumbuhan
# @name GetAllPlants
GET {{BaseUrl}}/plants?search=
Content-Type: application/json


#> {%
#    client.global.set("plantId", response.body.data.plants[0].id);
#    console.log(client.global.get("plantId"))
#%}



### Menambahkan data tumbuhan baru
# @name PostPlants
POST {{BaseUrl}}/plants
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Kangkung
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Brokoli adalah sayuran hijau yang kaya vitamin, mineral, dan serat
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Membantu detoksifikasi dan menjaga kesehatan mata
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Dapat menyebabkan kembung
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--

> {%
    client.global.set("plantId", response.body.data.plantId);
    console.log(client.global.get("plantId"))
%}

### Mengambil data tumbuhan berdasarkan id-nya
# @name GetPlantById
GET {{BaseUrl}}/plants/{{plantId}}
Content-Type: application/json

### Melihat gambar tumbuhan
# @name GetPlantImageById
GET {{BaseUrl}}/plants/{{plantId}}/image
Content-Type: application/json

### Mengubah hanya data plant berdasarkan id-nya
# @name PutPlantOnlyData
PUT {{BaseUrl}}/plants/{{plantId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Brokoli Update
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Brokoli adalah sayuran hijau yang kaya vitamin, mineral, dan serat
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Membantu detoksifikasi dan menjaga kesehatan mata
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Dapat menyebabkan kembung
--WebAppBoundary--

### Mengubah gambar dan data plant berdasarkan id-nya
# @name PutPlant
PUT {{BaseUrl}}/plants/{{plantId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Brokoli
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Brokoli adalah sayuran hijau yang kaya vitamin, mineral, dan serat
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Membantu detoksifikasi dan menjaga kesehatan mata
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Dapat menyebabkan kembung
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--

### Menghapus data plant berdasarkan id-nya
# @name DeletePlant
DELETE {{BaseUrl}}/plants/{{plantId}}
Content-Type: application/json

############################################
## BOOKS
############################################

### Mengambil semua data buku
# @name GetAllBooks
GET {{BaseUrl}}/books?search=
Accept: application/json

> {%
    if (response.body.data.books.length > 0) {
        client.global.set("bookId", response.body.data.books[0].id);
        console.log("bookId:", client.global.get("bookId"));
    }
%}


### Menambahkan data buku baru
# @name PostBook
POST {{BaseUrl}}/books
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="title"

Bumi
--WebAppBoundary
Content-Disposition: form-data; name="description"

Bumi adalah sebuah novel fiksi ilmiah fantasi yang menceritakan petualangan remaja di dunia paralel.
--WebAppBoundary
Content-Disposition: form-data; name="genre"

Fiksi Ilmiah, Fantasi
--WebAppBoundary
Content-Disposition: form-data; name="mainCharacter"

Raib, Seli, dan Ali
--WebAppBoundary
Content-Disposition: form-data; name="author"

Tere Liye
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--

> {%
    client.global.set("bookId", response.body.data.bookId);
    console.log("bookId:", client.global.get("bookId"));
%}


### Mengambil data buku berdasarkan id-nya
# @name GetBookById
GET {{BaseUrl}}/books/{{bookId}}
Accept: application/json


### Melihat gambar buku
# @name GetBookImageById
GET {{BaseUrl}}/books/{{bookId}}/image
Accept: image/*


### Mengubah hanya data buku berdasarkan id-nya
# @name PutBookOnlyData
PUT {{BaseUrl}}/books/{{bookId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="title"

Bumi (Edisi Revisi)
--WebAppBoundary
Content-Disposition: form-data; name="description"

Bumi adalah sebuah novel fiksi ilmiah fantasi yang menceritakan petualangan remaja di dunia paralel.
--WebAppBoundary
Content-Disposition: form-data; name="genre"

Fiksi Ilmiah, Fantasi
--WebAppBoundary
Content-Disposition: form-data; name="mainCharacter"

Raib, Seli, dan Ali
--WebAppBoundary
Content-Disposition: form-data; name="author"

Tere Liye
--WebAppBoundary--


### Mengubah gambar dan data buku berdasarkan id-nya
# @name PutBook
PUT {{BaseUrl}}/books/{{bookId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="title"

Bumi (Edisi Kolektor)
--WebAppBoundary
Content-Disposition: form-data; name="description"

Bumi adalah sebuah novel fiksi ilmiah fantasi yang menceritakan petualangan remaja di dunia paralel.
--WebAppBoundary
Content-Disposition: form-data; name="genre"

Fiksi Ilmiah, Fantasi
--WebAppBoundary
Content-Disposition: form-data; name="mainCharacter"

Raib, Seli, dan Ali
--WebAppBoundary
Content-Disposition: form-data; name="author"

Tere Liye
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--


### Menghapus data buku berdasarkan id-nya
# @name DeleteBook
DELETE {{BaseUrl}}/books/{{bookId}}
Accept: application/json